### ISSUE TITLE
Add plugin for J2K decoding

### ISSUE THREAD

**Issue by scaramallion** [pydicom/pylibjpeg#28]
Add support for JPEG2000 files by wrapping [openjpeg ](https://github.com/uclouvain/openjpeg)in a new plugin `pylibjpeg-openjpeg`

**Comment by jacksonofalltrades** [comment]
@scaramallion Any idea when this feature will be available?

**Comment by scaramallion** [comment]
I've been busy with other stuff, probably around July/August

**Comment by scaramallion** [comment]
Done, you'll either have to wait a bit for the v1.1 release or use the `master` branch with the [pylibjpeg-openjpeg](https://pypi.org/project/pylibjpeg-openjpeg/1.0.0/) plugin.
