### ISSUE TITLE
Tried to use this to parse a DICOM file and still am just getting a solid green image

### ISSUE THREAD

**Issue by jacksonofalltrades** [pydicom/pylibjpeg#41]
Details:
Lossy compression with JPEG baseline, IJG quality factor 100, compression ratio 3.5922
(0002, 0010) Transfer Syntax UID                 UI: JPEG Baseline (Process 1)

Even following readme instructions and importing pylibjpeg before trying to read pixel_array, I get this error:
OSError: broken data stream when reading image file

I've attached the DICOM file that has this problem. Please advise! Thank you.
[1.3.6.1.4.1.30071.6.203050750883198.3657180267111537.dcm.gz](https://github.com/pydicom/pylibjpeg/files/4690930/1.3.6.1.4.1.30071.6.203050750883198.3657180267111537.dcm.gz)

**Comment by jacksonofalltrades** [comment]
Correction: I had not seen how to install the jpeg plugin, am trying that now. Will close if that fixes!

**Comment by jacksonofalltrades** [comment]
Closing, that fixed it. Thank you.

**Comment by jacksonofalltrades** [comment]
Actually, although I do get a pixel array without errors, now, when I try to write the image it still has mostly green in it. Please advise?

**Comment by jacksonofalltrades** [comment]
Output attached.
![1 3 6 1 4 1 30071 6 17171705996 5259616659525711](https://user-images.githubusercontent.com/284967/83059396-b1ba8a00-a00e-11ea-9254-86a48c2778c5.jpg)

**Comment by jacksonofalltrades** [comment]
Ok more info: I tried forcing this to be interpeted by PIL as RGB and then I can write this out to look correct. My code was assuming however that this should be written out as "YCbCr" since the Photometric Interpretation is YBR_FULL_422. Should I be checking other DICOM attributes to determine whether or not to use "YCbCr"?

**Comment by jacksonofalltrades** [comment]
Correct image attached forcing RGB image mode when writing out.
![test](https://user-images.githubusercontent.com/284967/83064690-07933000-a017-11ea-91ed-e3a24fa95b21.jpg)

**Comment by scaramallion** [comment]
*pydicom* returns the Pixel Data as-written, so if the Photometric Interpretation is `YBR_FULL_422` then you get back a YCbCr image. To convert to RGB you can use the [pydicom.pixel_data_handlers.util.convert_color_space()](https://pydicom.github.io/pydicom/stable/reference/generated/pydicom.pixel_data_handlers.util.html#pydicom.pixel_data_handlers.util.convert_color_space) function.

**Comment by scaramallion** [comment]
Ah, I misunderstood. It should be displayed as YCbCr but its coming back as RGB.

Let me take a look

**Comment by scaramallion** [comment]
OK, looking at the data inside the JPG file, the `SOF0` marker has three components with the component IDs: 'R', 'G', and 'B'. This is pretty standard when RGB data has been encoded rather than YCbCr. I think in this case the Photometric Interpretation should be 'RGB'.

**Comment by scaramallion** [comment]
For reference, heres the JPEG info:
```
=================== SOI marker at offset 0 ====================

------------- APP14 marker at offset 2, length 16 -------------
Adobe v100:
  64 00 00 00 00 00

------------- DQT marker at offset 18, length 69 --------------
Table destination ID: 0
Table precision: 0 (8-bit)
Quantization table:
   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1

------------- SOF0 marker at offset 87, length 19 -------------
Baseline sequential DCT
Sample size (px): 800 x 600
Sample precision (bits): 8
Number of component images: 3
  Component ID: R
    Horizontal sampling factor: 1
    Vertical sampling factor: 1
    Quantization table destination: 0
  Component ID: G
    Horizontal sampling factor: 1
    Vertical sampling factor: 1
    Quantization table destination: 0
  Component ID: B
    Horizontal sampling factor: 1
    Vertical sampling factor: 1
    Quantization table destination: 0

------------- DHT marker at offset 106, length 33 -------------
Lossless/DC Huffman, table ID: 0
   1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16
  01 00 01 04 03 01 01 01 00 00 00 00 00 00 00 00 : # codes
  00                                              : L = 1
  06                                              : L = 3
  04 05 07 08                                     : L = 4
  02 03 09                                        : L = 5
  0a                                              : L = 6
  01                                              : L = 7
  0b                                              : L = 8

------------ DHT marker at offset 139, length 112 -------------
AC Huffman, table ID: 0
   1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16
  00 01 03 03 03 02 03 04 04 08 0a 08 03 00 00 27 : # codes
  01                                              : L = 2
  02 03 04                                        : L = 3
  05 06 11                                        : L = 4
  00 07 12                                        : L = 5
  08 21                                           : L = 6
  13 14 31                                        : L = 7
  09 15 22 41                                     : L = 8
  32 51 52 61                                     : L = 9
  16 23 54 91 92 a1 a2 d1                         : L = 10
  17 18 33 42 62 97 a3 d3 d6 e1                   : L = 11
  0a 24 57 71 93 98 d2 d7                         : L = 12
  43 53 81                                        : L = 13
  19 25 56 72 34 55 82 b2 c1 f0 26 27 58 59 73 75 : L = 16
  83 63 66 b1 35 36 39 44 64 c2 c3 c4 1a 28 37 38 : L = 16
  74 76 88 b4 b6 b7 b8                            : L = 16

------------- SOS marker at offset 251, length 14 -------------
Number of image components: 3
  Component: R, DC table: 0, AC table: 0
  Component: G, DC table: 0, AC table: 0
  Component: B, DC table: 0, AC table: 0
Spectral selectors start-end: 0-63
Successive approximation bit high-low: 0-0

................... ENC marker at offset 263...................

399085 bytes of entropy-coded data
```
