### ISSUE TITLE
`RuntimeError: Unable to convert the Pixel Data as the 'pylibjpeg-libjpeg' plugin is not installed` when running the executable generated with PyInstaller (but not with the script.py)

### ISSUE THREAD

**Issue by bjce** [pydicom/pylibjpeg#63]
Hello 

First of all thank you very much to the developper of `pydicom`: it is really a great packages!

Here are my specification
`pyinstaller==4.3`
`pydicom==2.1.2`
`pylibjpeg==1.3.0`
`pylibjpeg-libjpeg==1.2.0`
`pylibjpeg-openjpeg==1.1.1`
`pylibjpeg-rle==1.1.0`
`Python 3.8.5`
`Ubunutu 20.04.2 LTS`

I run into a similar probalem as related in [#58](https://github.com/pydicom/pylibjpeg/issues/58): When I run the script (script.py), there is no problem and I can run it without any problem. However, I cannot run the executable that I created with PyInstaller because I get the message: 'RuntimeError: Unable to convert the Pixel Data as the 'pylibjpeg-libjpeg' plugin is not installed'. This executable strategy worked fine until I installed `pylibjpeg`. In the `script.py` I only import `pydicom` (and not `pylibjpeg`)

**Comment by Borda** [comment]
can you try running `import openjpeg` I guess it will crash with
```
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

**Comment by bjce** [comment]
@Borda Many thanks for your answer. Sorry for the late answer. Today the error disappeared. It might have been thanks to a computer restart. Many thanks again for the help
